import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import Logo from '../../public/images/logo/Frame 3 (1).png'
import { Three } from '@/features/sample/components/three'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
<<<<<<< HEAD
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="ja">
			<head>
				<meta charSet="UTF-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&family=Oswald:wght@200..700&family=Zen+Maru+Gothic&display=swap" rel="stylesheet"></link>
			</head>
			<body className={inter.className}>
				<div className='h-[100vh] w-full bg-[#21354C] relative z-[10]'>
					<div className='absolute w-full h-full'>
						<div className='top-0 flex items-center justify-center h-[15%] w-full'>
							<div className='w-[95%] h-[70%] flex justify-between'>
								<div className='h-full w-[10%] flex items-center'>
									<Image
										src={Logo}
										alt="ロゴ"
										width={65}
										height={65}
									/>
								</div>
								<div className='bg-gray-400 h-full w-[50%] flex items-center justify-end'>
									ここにヘッダー
								</div>
							</div>
						</div>
						<div className='h-[85%] w-full flex'>
							<div className='h-full w-[20%]'>
								<div className='w-full h-[50%] flex items-center justify-center'>
									<div className='w-fit h-fit rotate-90'>
										<p className='text-white font-nico tracking-[1rem] text-center '>
											TO THE <br /> POINT
										</p>
									</div>
								</div>
								<div className='w-[50%] h-[50%] flex items-end'>
									<div className='border-r border-solid border-white w-full h-full'>

									</div>
								</div>
							</div>
							<div className='h-full w-[80%]'>
								{children}
							</div>
						</div>
					</div>
					<div className='x-[0]'>
						<Three />
					</div>
				</div>
			</body>
		</html>
	)
=======
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ja">
            <body className="bg-customBackground">{children}</body>
        </html>
    )
>>>>>>> 2caf243c87fe900ead19168f2687687edf578ad3
}
